name: "Run SAST Scan on SuperMario Game Project"

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  sonarqube_sast_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Debug secrets being passed
        run: |
          echo "SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}"
          echo "SONAR_TOKEN exists: ${{ secrets.SONAR_TOKEN != '' }}"

      - name: Run SonarQube Scan with Maven
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=gitopsdevsecopspipeline \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.scanner.skip=false \
            -Dsonar.maven.skip=false \
            -Dsonar.search.host= \
            -Dsonar.projectBaseDir=. \
            -Dsonar.java.binaries=target/classes

      - name: Extract short commit SHA
        run: echo "COMMIT_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: andynze4/supermario:${{ env.COMMIT_ID }}